name: Test Pages publish

on:
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: payload
        run: |
          mkdir source
          cp index.md source/index.md

      - uses: actions/jekyll-build-pages@b178f9334b208360999a0a57b523613563698c66 # 1.0.12
        with:
          source: source
          destination: build-jekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.0
        with:
          path: build-jekyll

      - id: deployment
        uses: actions/deploy-pages@v4.0.3
